package entities.dao;
// Generated Mar 30, 2011 5:51:41 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private Integer courseId;
     private String courseName;
     private Integer teoricLectureHours;
     private Integer practiceLectureHourse;
     private String courseDescription;
     private String typeofCourse;
     private Integer attendance;
     private Set syllabuses = new HashSet(0);

    public Course() {
    }

    public Course(String courseName, Integer teoricLectureHours, Integer practiceLectureHourse, String courseDescription, String typeofCourse, Integer attendance, Set syllabuses) {
       this.courseName = courseName;
       this.teoricLectureHours = teoricLectureHours;
       this.practiceLectureHourse = practiceLectureHourse;
       this.courseDescription = courseDescription;
       this.typeofCourse = typeofCourse;
       this.attendance = attendance;
       this.syllabuses = syllabuses;
    }
   
    public void AddCourse(){
		Session session=null;
		try{
			
			SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
			session = sessionFactory.openSession();
			//System.out.println("Lecturer.java lecturerName:" + lecturerName);
			Query query = session.getNamedQuery("AddCourse");
			//System.out.println("Lecturer: AddLecturer2");
			//query.setParameter(, arg1)
			query.setParameter("pCourseName", courseName);
			query.setParameter("pTeoricLecturerHours", teoricLectureHours);
			query.setParameter("pPracticeLecturerHours", practiceLectureHourse);
			query.setParameter("pCourseDescription",courseDescription);
			query.setParameter("pTypeOfCourse", typeofCourse);
			query.setParameter("pAttandance", attendance);
			
			query.executeUpdate();
			
			//System.out.println("Lecturer: AddLecturer3");
			
		}catch(Exception e){
			System.err.print(e.getMessage());
		}
	}
    
    public Integer getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
    public String getCourseName() {
        return this.courseName;
    }
    
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }
    public Integer getTeoricLectureHours() {
        return this.teoricLectureHours;
    }
    
    public void setTeoricLectureHours(Integer teoricLectureHours) {
        this.teoricLectureHours = teoricLectureHours;
    }
    public Integer getPracticeLectureHourse() {
        return this.practiceLectureHourse;
    }
    
    public void setPracticeLectureHourse(Integer practiceLectureHourse) {
        this.practiceLectureHourse = practiceLectureHourse;
    }
    public String getCourseDescription() {
        return this.courseDescription;
    }
    
    public void setCourseDescription(String courseDescription) {
        this.courseDescription = courseDescription;
    }
    public String getTypeofCourse() {
        return this.typeofCourse;
    }
    
    public void setTypeofCourse(String typeofCourse) {
        this.typeofCourse = typeofCourse;
    }
    public Integer getAttendance() {
        return this.attendance;
    }
    
    public void setAttendance(Integer attendance) {
        this.attendance = attendance;
    }
    public Set getSyllabuses() {
        return this.syllabuses;
    }
    
    public void setSyllabuses(Set syllabuses) {
        this.syllabuses = syllabuses;
    }




}


