package entities.dao;

import org.hibernate.Query;


import org.hibernate.SQLQuery;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

// Generated Mar 30, 2011 4:46:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * Lecturer generated by hbm2java
 */
public class Lecturer implements java.io.Serializable {

	private Integer lecturerId;
	private String lecturerName;

	public Lecturer() {
	}

	public Lecturer(String lecturerName) {
		this.lecturerName = lecturerName;
	}

	public void AddLecturer(){
		Session session=null;
		try{
			
			SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
			session = sessionFactory.openSession();
			System.out.println("Lecturer: AddLecturer1");
			Query query = session.getNamedQuery("AddLecturer");
			System.out.println("Lecturer: AddLecturer2");
			query.setParameter("pLecturerName", lecturerName);
			query.executeUpdate();
			
			System.out.println("Lecturer: AddLecturer3");
			
		}catch(Exception e){
			System.err.print(e.getMessage());
		}
	}
	
	public Integer getLecturerId() {
		return this.lecturerId;
	}

	public void setLecturerId(Integer lecturerId) {
		this.lecturerId = lecturerId;
	}

	public String getLecturerName() {
		return this.lecturerName;
	}

	public void setLecturerName(String lecturerName) {
		this.lecturerName = lecturerName;
	}

}
