package entities.dao;

// Generated Mar 26, 2011 8:57:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Lecturer generated by hbm2java
 */
public class Lecturer implements java.io.Serializable {

	private Integer lecturerId;
	private String lecturerName;
	private Set syllabuses = new HashSet(0);

	public Lecturer() {
	}

	public Lecturer(String lecturerName, Set syllabuses) {
		this.lecturerName = lecturerName;
		this.syllabuses = syllabuses;
	}

	public Integer getLecturerId() {
		return this.lecturerId;
	}

	public void setLecturerId(Integer lecturerId) {
		this.lecturerId = lecturerId;
	}

	public String getLecturerName() {
		return this.lecturerName;
	}

	public void setLecturerName(String lecturerName) {
		this.lecturerName = lecturerName;
	}

	public Set getSyllabuses() {
		return this.syllabuses;
	}

	public void setSyllabuses(Set syllabuses) {
		this.syllabuses = syllabuses;
	}

}
