package entities.dao;

// Generated Mar 30, 2011 4:46:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * Syllabus generated by hbm2java
 */
public class Syllabus implements java.io.Serializable {

	private Integer syllabusId;
	private int courseId;
	private int lecturerId;

	public Syllabus() {
	}

	public Syllabus(int courseId, int lecturerId) {
		this.courseId = courseId;
		this.lecturerId = lecturerId;
	}

	public Integer getSyllabusId() {
		return this.syllabusId;
	}

	public void setSyllabusId(Integer syllabusId) {
		this.syllabusId = syllabusId;
	}

	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	public int getLecturerId() {
		return this.lecturerId;
	}

	public void setLecturerId(int lecturerId) {
		this.lecturerId = lecturerId;
	}

}
