package entities.dao;

// Generated Mar 26, 2011 8:57:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * Syllabus generated by hbm2java
 */
public class Syllabus implements java.io.Serializable {

	private Integer syllabusId;
	private Lecturer lecturer;
	private Course course;

	public Syllabus() {
	}

	public Syllabus(Lecturer lecturer, Course course) {
		this.lecturer = lecturer;
		this.course = course;
	}

	public Integer getSyllabusId() {
		return this.syllabusId;
	}

	public void setSyllabusId(Integer syllabusId) {
		this.syllabusId = syllabusId;
	}

	public Lecturer getLecturer() {
		return this.lecturer;
	}

	public void setLecturer(Lecturer lecturer) {
		this.lecturer = lecturer;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

}
