package entities.dao;

// Generated Mar 26, 2011 8:57:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * SyllabusArchive generated by hbm2java
 */
public class SyllabusArchive implements java.io.Serializable {

	private Integer syllabusArchiveId;
	private String semesterName;
	private String filePath;

	public SyllabusArchive() {
	}

	public SyllabusArchive(String semesterName, String filePath) {
		this.semesterName = semesterName;
		this.filePath = filePath;
	}

	public Integer getSyllabusArchiveId() {
		return this.syllabusArchiveId;
	}

	public void setSyllabusArchiveId(Integer syllabusArchiveId) {
		this.syllabusArchiveId = syllabusArchiveId;
	}

	public String getSemesterName() {
		return this.semesterName;
	}

	public void setSemesterName(String semesterName) {
		this.semesterName = semesterName;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

}
