package entities.dao;

// Generated Mar 26, 2011 8:57:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * SysUser generated by hbm2java
 */
public class SysUser implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userStatus;

	public SysUser() {
	}

	public SysUser(String userName, String userStatus) {
		this.userName = userName;
		this.userStatus = userStatus;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

}
