package entities.dao;

// Generated Apr 11, 2011 11:14:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

/**
 * Classroom generated by hbm2java
 */
public class Classroom implements java.io.Serializable {

	private Integer classroomId;
	private String classroomCode;
	private Department department;
	private Set syllabuses = new HashSet(0);
	
	public Classroom() {
	}

	public Classroom(String classroomCode) {
		this.classroomCode = classroomCode;
	}

	public Classroom(String classroomCode, Department department, Set syllabuses) {
		this.classroomCode = classroomCode;
		this.department = department;
		this.syllabuses = syllabuses;
	}

	/*Copy constructor added by Erhun 18.04.2011*/
	public Classroom (Classroom classroom){
		this.classroomId = classroom.classroomId;
		this.classroomCode = classroom.classroomCode;
		this.department = classroom.department;
		this.syllabuses = classroom.syllabuses;
	}
	
	@SuppressWarnings("unchecked")
	public List<Classroom> getAllClassroom(){
		List<Classroom> allClassroom = null;
		
		 
         Session session = null;
         
         try {
                 SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
                 session = sessionFactory.openSession();
                 
                 Query query = session.getNamedQuery("getAllClassroom");
                 allClassroom =(List<Classroom>) query.list();
                 
         } catch (Exception e) {
                 // TODO: handle exception
                 e.getMessage();
         } 
         return allClassroom;
	}
	
	public void addClassroom(){
		Session session=null;
		try{
			
			SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
			session = sessionFactory.openSession();
			Transaction tx = session.beginTransaction();
			Query query = session.getNamedQuery("addClassroom");
			query.setParameter("pClassroomCode", classroomCode);
			query.setParameter("pDepartmentId", department );
			query.executeUpdate();
			tx.commit();
			
		}catch(Exception e){
			System.err.print(e.getMessage());
		}
		finally{
			session.close();
			
		}
	}
	
	public void deleteClassroom(){
		Session session=null;
		try{
			
			SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
			session = sessionFactory.openSession();
			Transaction tx = session.beginTransaction();
			Query query = session.getNamedQuery("deleteClassroom");
			query.setParameter("pClassroomId", classroomId);
			query.executeUpdate();
			tx.commit();
		}catch(Exception e){
			System.err.print(e.getMessage());
		}
		finally{
			session.close();
		}
	}

	public void updateClassroom() throws Exception{
		Session session=null;
		try{
			
			SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
			session = sessionFactory.openSession();
			Transaction tx = session.beginTransaction();
			Query query = session.getNamedQuery("updateClassroom");
			query.setParameter("pClassroomId", classroomId);
			query.setParameter("pClassroomCode", classroomCode);
			query.setParameter("pDepartmentId", department);
			query.executeUpdate();
			tx.commit();
		}catch(Exception e){
			System.err.print(e.getMessage());
			throw new Exception(e);
		}
		finally{
			session.close();
		}
	}
	
	
	public Integer getClassroomId() {
		return this.classroomId;
	}

	public void setClassroomId(Integer classroomId) {
		this.classroomId = classroomId;
	}

	public String getClassroomCode() {
		return this.classroomCode;
	}

	public void setClassroomCode(String classroomCode) {
		this.classroomCode = classroomCode;
	}

	public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public Set getSyllabuses() {
		return syllabuses;
	}

	public void setSyllabuses(Set syllabuses) {
		this.syllabuses = syllabuses;
	}
}
