package entities.dao;

import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
// Generated Apr 11, 2011 11:14:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Lecturer generated by hbm2java
 */
public class Lecturer implements java.io.Serializable {

	private Integer lecturerId;
	private Department department;
	private String lecturerName;
	private String title;
	private String email;
	private String telephone;
	private Set syllabuses = new HashSet(0);

	public Lecturer() {
	}

	public Lecturer(Department department, String lecturerName, String title) {
		this.department = department;
		this.lecturerName = lecturerName;
		this.title = title;
	}

	public Lecturer(Department department, String lecturerName, String title,
			String email, String telephone, Set syllabuses) {
		this.department = department;
		this.lecturerName = lecturerName;
		this.title = title;
		this.email = email;
		this.telephone = telephone;
		this.syllabuses = syllabuses;
	}

	@SuppressWarnings("unchecked")
	public List<Lecturer> getIdByLecturerName(){
		List<Lecturer> lecturerNameList = null;
		
        Session session = null;
        
        try {
                SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
                session = sessionFactory.openSession();
                
                Query query = session.getNamedQuery("getIdByLecturerName");
                
                query.setParameter("pLecturerName", lecturerName);
                lecturerNameList = (List<Lecturer>) query.list();
                
        } catch (Exception e) {
                // TODO: handle exception
                e.getMessage();
        } 
        return lecturerNameList;
	}
	
	public List<Lecturer> getAllLecturer(){
		List<Lecturer> allLecturerList = null;
		Session session = null;
		
		try {
			SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
			session = sessionFactory.openSession();
			
			Query query = session.getNamedQuery("getAllLecturer");
			allLecturerList = (List<Lecturer>) query.list();
		} catch (HibernateException e) {
			// TODO Auto-generated catch block
			e.getMessage();
		}
		return allLecturerList;
	}
	
	public void AddLecturer(){
        Session session=null;
        try{
                
                SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
                session = sessionFactory.openSession();
                Query query = session.getNamedQuery("AddLecturer");
                query.setParameter("pLecturerName", lecturerName);
                query.setParameter("pTitle", "Dr.");
                query.setParameter("pDepartment", "CS");
                query.setParameter("pEmail", "ulas.cs.deu.edu.tr");
                query.setParameter("pTelephone", "77777777777");
                query.executeUpdate();
                
                System.out.println("Lecturer:" + lecturerName + " is added.");
                
        }catch(Exception e){
                System.err.print(e.getMessage());
        }
}
	
	public Integer getLecturerId() {
		return this.lecturerId;
	}

	public void setLecturerId(Integer lecturerId) {
		this.lecturerId = lecturerId;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public String getLecturerName() {
		return this.lecturerName;
	}

	public void setLecturerName(String lecturerName) {
		this.lecturerName = lecturerName;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public Set getSyllabuses() {
		return this.syllabuses;
	}

	public void setSyllabuses(Set syllabuses) {
		this.syllabuses = syllabuses;
	}

}
