package entities.dao;

// Generated Mar 31, 2011 9:47:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * Lecturer generated by hbm2java
 */
public class Lecturer implements java.io.Serializable {

	private Integer lecturerId;
	private String lecturerName;
	private String title;
	private String department;
	private String email;
	private String telephone;

	public Lecturer() {
	}

	public Lecturer(String lecturerName, String title, String department) {
		this.lecturerName = lecturerName;
		this.title = title;
		this.department = department;
	}

	public Lecturer(String lecturerName, String title, String department,
			String email, String telephone) {
		this.lecturerName = lecturerName;
		this.title = title;
		this.department = department;
		this.email = email;
		this.telephone = telephone;
	}

	public Integer getLecturerId() {
		return this.lecturerId;
	}

	public void setLecturerId(Integer lecturerId) {
		this.lecturerId = lecturerId;
	}

	public String getLecturerName() {
		return this.lecturerName;
	}

	public void setLecturerName(String lecturerName) {
		this.lecturerName = lecturerName;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

}
