package entities.dao;

// Generated Mar 31, 2011 9:47:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * Schedule generated by hbm2java
 */
public class Schedule implements java.io.Serializable {

	private Integer scheduleId;
	private String courseType;
	private int timeofCourse;
	private int courseId;

	public Schedule() {
	}

	public Schedule(String courseType, int timeofCourse, int courseId) {
		this.courseType = courseType;
		this.timeofCourse = timeofCourse;
		this.courseId = courseId;
	}

	public Integer getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(Integer scheduleId) {
		this.scheduleId = scheduleId;
	}

	public String getCourseType() {
		return this.courseType;
	}

	public void setCourseType(String courseType) {
		this.courseType = courseType;
	}

	public int getTimeofCourse() {
		return this.timeofCourse;
	}

	public void setTimeofCourse(int timeofCourse) {
		this.timeofCourse = timeofCourse;
	}

	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

}
