package entities.dao;

// Generated Mar 31, 2011 9:47:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * SyllabusArchive generated by hbm2java
 */
public class SyllabusArchive implements java.io.Serializable {

	private Integer syllabusArchiveId;
	private String semester;
	private int year;
	private String filePath;

	public SyllabusArchive() {
	}

	public SyllabusArchive(String semester, int year, String filePath) {
		this.semester = semester;
		this.year = year;
		this.filePath = filePath;
	}

	public Integer getSyllabusArchiveId() {
		return this.syllabusArchiveId;
	}

	public void setSyllabusArchiveId(Integer syllabusArchiveId) {
		this.syllabusArchiveId = syllabusArchiveId;
	}

	public String getSemester() {
		return this.semester;
	}

	public void setSemester(String semester) {
		this.semester = semester;
	}

	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

}
