package entities.dao;
import java.util.List;

import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

// Generated Apr 11, 2011 11:14:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Syllabus generated by hbm2java
 */
public class Syllabus implements java.io.Serializable {

	private Integer syllabusId;
	private Lecturer lecturer;
	private Course course;
	private String semester;
	private int year;
	private Integer sectionNo;
	private Classroom classroom;
	private Set schedules = new HashSet(0);

	public Syllabus() {
	}

	public Syllabus(Lecturer lecturer, Course course, String semester, int year) {
		this.lecturer = lecturer;
		this.course = course;
		this.semester = semester;
		this.year = year;
	}

	public Syllabus(Lecturer lecturer, Course course, String semester, int year, Integer sectionNo, Classroom classroom, Set schedules) {
		this.lecturer = lecturer;
		this.course = course;
		this.semester = semester;
		this.year = year;
		this.sectionNo = sectionNo;
		this.classroom = classroom;
		this.schedules = schedules;
	}
	
	/*Copy constructor Added by Erhun 16.04.2011*/
	public Syllabus(Syllabus syllabus){
		this.syllabusId = syllabus.getSyllabusId();
		this.semester = syllabus.getSemester();
		this.year = syllabus.getYear();
		this.course = syllabus.getCourse();
		this.lecturer = syllabus.getLecturer();
		this.sectionNo = syllabus.getSectionNo();
		this.schedules = syllabus.getSchedules();
		this.classroom = syllabus.getClassroom();
	}
	
	public void deleteSyllabus(){
		
		Session session=null;
		try{
			
			SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
			session = sessionFactory.openSession();
			Transaction tx = session.beginTransaction();
			Query query = session.getNamedQuery("DeleteSyllabus");
			query.setParameter("pSyllabusId", syllabusId);
			query.executeUpdate();
			tx.commit();
		}catch(Exception e){
			System.err.print(e.getMessage());
		}
		finally{
			session.close();
		}
	}
	
public void updateSyllabus(){
		
		Session session=null;
		try{
			
			SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
			session = sessionFactory.openSession();
			Transaction tx = session.beginTransaction();
			Query query = session.getNamedQuery("UpdateSyllabus");
			query.setParameter("pSyllabusId", syllabusId);
			query.setParameter("pSemester", semester);
			query.setParameter("pYear", year);
			query.setParameter("pCourseId", this.getCourse().getCourseId());
			query.setParameter("pLecturerId", this.getLecturer().getLecturerId());
			query.setParameter("pSectionNo", sectionNo);
			query.executeUpdate();
			tx.commit();
		}catch(Exception e){
			System.err.print(e.getMessage());
		}
		finally{
			session.close();
		}
	}

public void addSyllabus(){
	
	Session session=null;
	try{
		
		SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
		session = sessionFactory.openSession();
		Transaction tx = session.beginTransaction();
		Query query = session.getNamedQuery("AddSyllabus");
		query.setParameter("pSemester", semester);
		query.setParameter("pYear", year);
		query.setParameter("pCourseId", course.getCourseId());
		query.setParameter("pLecturerId", lecturer.getLecturerId());
		query.setParameter("pSectionNo", sectionNo);
		query.executeUpdate();
		tx.commit();
	}catch(Exception e){
		System.err.print(e.getMessage());
	}
	finally{
		session.close();
	}
}

    @SuppressWarnings("unchecked")
	public List<Syllabus> getSyllabusBySemesterAndGrade(){
		List<Syllabus> allSyllabus = null;
		
         Session session = null;
         
         try {
                 SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
                 session = sessionFactory.openSession();
                 
                 Query query = session.getNamedQuery("getSyllabusBySemesterAndGrade");
                 query.setParameter("pGrade", course.getGrade());
                 query.setParameter("pSemester", semester);
                 allSyllabus =(List<Syllabus>) query.list();
                 
         } catch (Exception e) {
                 // TODO: handle exception
                 e.getMessage();
         } 
         return allSyllabus;
	}
    
	@SuppressWarnings("unchecked")
	public List<Syllabus> getAllSyllabus(){
		List<Syllabus> allSyllabus = null;
		
         Session session = null;
         
         try {
                 SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
                 session = sessionFactory.openSession();
                 
                 Query query = session.getNamedQuery("getAllSyllabus");
                 allSyllabus =(List<Syllabus>) query.list();
                 
         } catch (Exception e) {
                 // TODO: handle exception
                 e.getMessage();
         } 
         return allSyllabus;
	}

	public Integer getSyllabusId() {
		return this.syllabusId;
	}

	public void setSyllabusId(Integer syllabusId) {
		this.syllabusId = syllabusId;
	}

	public Lecturer getLecturer() {
		return this.lecturer;
	}

	public void setLecturer(Lecturer lecturer) {
		this.lecturer = lecturer;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public String getSemester() {
		return this.semester;
	}

	public void setSemester(String semester) {
		this.semester = semester;
	}

	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public Integer getSectionNo() {
		return this.sectionNo;
	}

	public void setSectionNo(Integer sectionNo) {
		this.sectionNo = sectionNo;
	}

	public Set getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set schedules) {
		this.schedules = schedules;
	}

	public Classroom getClassroom() {
		return classroom;
	}

	public void setClassroom(Classroom classroom) {
		this.classroom = classroom;
	}

	
}
