package entities.dao;

import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;


import java.util.List;


// Generated Mar 31, 2011 9:47:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * SysUser generated by hbm2java
 */
@SuppressWarnings("serial")
public class SysUser implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userStatus;
	private String userPassword;

	public SysUser() {
	}

	public SysUser(String userName, String userStatus, String userPassword) {
		this.userName = userName;
		this.userStatus = userStatus;
		this.userPassword = userPassword;
	}

	
	@SuppressWarnings("unchecked")
	public List<SysUser> getAllUser(){
		List<SysUser> allUser = null;
		
		 //List<TestUser> result = null;
         Session session = null;
         
         try {
                 SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
                 session = sessionFactory.openSession();
                 
                 Query query = session.getNamedQuery("getAllUser");
                 allUser =(List<SysUser>) query.list();
                 
         } catch (Exception e) {
                 // TODO: handle exception
                 e.getMessage();
         } 
         return allUser;
	}
	
	public void deleteUser(){
		Session session=null;
		try{
			
			SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
			session = sessionFactory.openSession();
			Query query = session.getNamedQuery("DeleteUser");
			query.setParameter("pUserId", userId);
			query.executeUpdate();
		}catch(Exception e){
			System.err.print(e.getMessage());
		}
	}
	
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

}
