package entities.dao;

// Generated Mar 31, 2011 9:47:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * TypeofCourse generated by hbm2java
 */
public class TypeofCourse implements java.io.Serializable {

	private Integer typeofCourseId;
	private String typeofCourse;

	public TypeofCourse() {
	}

	public TypeofCourse(String typeofCourse) {
		this.typeofCourse = typeofCourse;
	}

	public Integer getTypeofCourseId() {
		return this.typeofCourseId;
	}

	public void setTypeofCourseId(Integer typeofCourseId) {
		this.typeofCourseId = typeofCourseId;
	}

	public String getTypeofCourse() {
		return this.typeofCourse;
	}

	public void setTypeofCourse(String typeofCourse) {
		this.typeofCourse = typeofCourse;
	}

}
