package entities.dao;

// Generated Apr 11, 2011 11:14:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

import com.sun.faces.mgbean.ManagedBeanPreProcessingException.Type;

/**
 * TypeofCourse generated by hbm2java
 */
public class TypeofCourse implements java.io.Serializable {

	private Integer typeofCourseId;
	private String typeofCourse;
	private Set courses = new HashSet(0);

	public TypeofCourse() {
	}

	public List<TypeofCourse> getAllTypeofCourses(){
		List<TypeofCourse> typeofCoursesList = null;
		Session session = null;
		
		try {
			SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
			session = sessionFactory.openSession();
			
			Query query = session.getNamedQuery("getAllTypeofCourses");
			typeofCoursesList = (List<TypeofCourse>) query.list();
		} catch (HibernateException e) {
			// TODO Auto-generated catch block
			e.getMessage();
		} 
		return typeofCoursesList;
	}
	
	public List<TypeofCourse> getTypeofCourseByCode(){
		List<TypeofCourse> tocList = null;
		
        Session session = null;
        
        try {
                SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
                session = sessionFactory.openSession();
                
                Query query = session.getNamedQuery("getTypeofCourseByCode");
                
                query.setParameter("pTypeofCourseCode", typeofCourse);
                tocList = (List<TypeofCourse>) query.list();
                
        } catch (Exception e) {
                // TODO: handle exception
                e.getMessage();
        } 
        return tocList;
		
	}
	
	public TypeofCourse(String typeofCourse) {
		this.typeofCourse = typeofCourse;
	}

	public TypeofCourse(String typeofCourse, Set courses) {
		this.typeofCourse = typeofCourse;
		this.courses = courses;
	}

	public Integer getTypeofCourseId() {
		return this.typeofCourseId;
	}

	public void setTypeofCourseId(Integer typeofCourseId) {
		this.typeofCourseId = typeofCourseId;
	}

	public String getTypeofCourse() {
		return this.typeofCourse;
	}

	public void setTypeofCourse(String typeofCourse) {
		this.typeofCourse = typeofCourse;
	}

	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

}
