package entities.dao;

// Generated Apr 11, 2011 8:27:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Classroom generated by hbm2java
 */
public class Classroom implements java.io.Serializable {

	private Integer classroomId;
	private String classroomCode;
	private Set schedules = new HashSet(0);

	public Classroom() {
	}

	public Classroom(String classroomCode) {
		this.classroomCode = classroomCode;
	}

	public Classroom(String classroomCode, Set schedules) {
		this.classroomCode = classroomCode;
		this.schedules = schedules;
	}

	public Integer getClassroomId() {
		return this.classroomId;
	}

	public void setClassroomId(Integer classroomId) {
		this.classroomId = classroomId;
	}

	public String getClassroomCode() {
		return this.classroomCode;
	}

	public void setClassroomCode(String classroomCode) {
		this.classroomCode = classroomCode;
	}

	public Set getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set schedules) {
		this.schedules = schedules;
	}

}
