package entities.dao;

// Generated 04.May.2011 23:43:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private Integer courseId;
	private TypeofCourse typeofCourse;
	private Department department;
	private String courseCode;
	private String courseName;
	private int teoricLectureHours;
	private int practiceLectureHourse;
	private boolean attendance;
	private int grade;
	private String precondition;
	private String courseDescription;
	private Set syllabuses = new HashSet(0);

	public Course() {
	}

	public Course(TypeofCourse typeofCourse, Department department,
			String courseCode, String courseName, int teoricLectureHours,
			int practiceLectureHourse, boolean attendance, int grade) {
		this.typeofCourse = typeofCourse;
		this.department = department;
		this.courseCode = courseCode;
		this.courseName = courseName;
		this.teoricLectureHours = teoricLectureHours;
		this.practiceLectureHourse = practiceLectureHourse;
		this.attendance = attendance;
		this.grade = grade;
	}

	public Course(TypeofCourse typeofCourse, Department department,
			String courseCode, String courseName, int teoricLectureHours,
			int practiceLectureHourse, boolean attendance, int grade,
			String precondition, String courseDescription, Set syllabuses) {
		this.typeofCourse = typeofCourse;
		this.department = department;
		this.courseCode = courseCode;
		this.courseName = courseName;
		this.teoricLectureHours = teoricLectureHours;
		this.practiceLectureHourse = practiceLectureHourse;
		this.attendance = attendance;
		this.grade = grade;
		this.precondition = precondition;
		this.courseDescription = courseDescription;
		this.syllabuses = syllabuses;
	}

	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	public TypeofCourse getTypeofCourse() {
		return this.typeofCourse;
	}

	public void setTypeofCourse(TypeofCourse typeofCourse) {
		this.typeofCourse = typeofCourse;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public String getCourseCode() {
		return this.courseCode;
	}

	public void setCourseCode(String courseCode) {
		this.courseCode = courseCode;
	}

	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public int getTeoricLectureHours() {
		return this.teoricLectureHours;
	}

	public void setTeoricLectureHours(int teoricLectureHours) {
		this.teoricLectureHours = teoricLectureHours;
	}

	public int getPracticeLectureHourse() {
		return this.practiceLectureHourse;
	}

	public void setPracticeLectureHourse(int practiceLectureHourse) {
		this.practiceLectureHourse = practiceLectureHourse;
	}

	public boolean isAttendance() {
		return this.attendance;
	}

	public void setAttendance(boolean attendance) {
		this.attendance = attendance;
	}

	public int getGrade() {
		return this.grade;
	}

	public void setGrade(int grade) {
		this.grade = grade;
	}

	public String getPrecondition() {
		return this.precondition;
	}

	public void setPrecondition(String precondition) {
		this.precondition = precondition;
	}

	public String getCourseDescription() {
		return this.courseDescription;
	}

	public void setCourseDescription(String courseDescription) {
		this.courseDescription = courseDescription;
	}

	public Set getSyllabuses() {
		return this.syllabuses;
	}

	public void setSyllabuses(Set syllabuses) {
		this.syllabuses = syllabuses;
	}

}
