package entities.dao;

// Generated Apr 11, 2011 8:27:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Lecturer generated by hbm2java
 */
public class Lecturer implements java.io.Serializable {

	private Integer lecturerId;
	private Department department;
	private String lecturerName;
	private String title;
	private String email;
	private String telephone;
	private Set syllabuses = new HashSet(0);

	public Lecturer() {
	}

	public Lecturer(Department department, String lecturerName, String title) {
		this.department = department;
		this.lecturerName = lecturerName;
		this.title = title;
	}

	public Lecturer(Department department, String lecturerName, String title,
			String email, String telephone, Set syllabuses) {
		this.department = department;
		this.lecturerName = lecturerName;
		this.title = title;
		this.email = email;
		this.telephone = telephone;
		this.syllabuses = syllabuses;
	}

	public Integer getLecturerId() {
		return this.lecturerId;
	}

	public void setLecturerId(Integer lecturerId) {
		this.lecturerId = lecturerId;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public String getLecturerName() {
		return this.lecturerName;
	}

	public void setLecturerName(String lecturerName) {
		this.lecturerName = lecturerName;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public Set getSyllabuses() {
		return this.syllabuses;
	}

	public void setSyllabuses(Set syllabuses) {
		this.syllabuses = syllabuses;
	}

}
