package entities.dao;

// Generated Apr 11, 2011 8:27:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Schedule generated by hbm2java
 */
public class Schedule implements java.io.Serializable {

	private Integer scheduleId;
	private Classroom classroom;
	private Syllabus syllabus;
	private String courseType;
	private int timeofCourse;
	private int hours;

	public Schedule() {
	}

	public Schedule(Classroom classroom, Syllabus syllabus, String courseType,
			int timeofCourse, int hours) {
		this.classroom = classroom;
		this.syllabus = syllabus;
		this.courseType = courseType;
		this.timeofCourse = timeofCourse;
		this.hours = hours;
	}

	public Integer getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(Integer scheduleId) {
		this.scheduleId = scheduleId;
	}

	public Classroom getClassroom() {
		return this.classroom;
	}

	public void setClassroom(Classroom classroom) {
		this.classroom = classroom;
	}

	public Syllabus getSyllabus() {
		return this.syllabus;
	}

	public void setSyllabus(Syllabus syllabus) {
		this.syllabus = syllabus;
	}

	public String getCourseType() {
		return this.courseType;
	}

	public void setCourseType(String courseType) {
		this.courseType = courseType;
	}

	public int getTimeofCourse() {
		return this.timeofCourse;
	}

	public void setTimeofCourse(int timeofCourse) {
		this.timeofCourse = timeofCourse;
	}

	public int getHours() {
		return this.hours;
	}

	public void setHours(int hours) {
		this.hours = hours;
	}

}
