package entities.dao;

// Generated 04.May.2011 23:43:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Syllabus generated by hbm2java
 */
public class Syllabus implements java.io.Serializable {

	private Integer syllabusId;
	private Course course;
	private Lecturer lecturer;
	private String semester;
	private int year;
	private Integer sectionNo;
	private Set schedules = new HashSet(0);

	public Syllabus() {
	}

	public Syllabus(Course course, Lecturer lecturer, String semester, int year) {
		this.course = course;
		this.lecturer = lecturer;
		this.semester = semester;
		this.year = year;
	}

	public Syllabus(Course course, Lecturer lecturer, String semester,
			int year, Integer sectionNo, Set schedules) {
		this.course = course;
		this.lecturer = lecturer;
		this.semester = semester;
		this.year = year;
		this.sectionNo = sectionNo;
		this.schedules = schedules;
	}

	public Integer getSyllabusId() {
		return this.syllabusId;
	}

	public void setSyllabusId(Integer syllabusId) {
		this.syllabusId = syllabusId;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Lecturer getLecturer() {
		return this.lecturer;
	}

	public void setLecturer(Lecturer lecturer) {
		this.lecturer = lecturer;
	}

	public String getSemester() {
		return this.semester;
	}

	public void setSemester(String semester) {
		this.semester = semester;
	}

	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public Integer getSectionNo() {
		return this.sectionNo;
	}

	public void setSectionNo(Integer sectionNo) {
		this.sectionNo = sectionNo;
	}

	public Set getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set schedules) {
		this.schedules = schedules;
	}

}
