package entities.dao;

// Generated 04.May.2011 23:43:59 by Hibernate Tools 3.4.0.CR1

/**
 * SyllabusArchive generated by hbm2java
 */
public class SyllabusArchive implements java.io.Serializable {

	private Integer syllabusArchiveId;
	private String semester;
	private int year;
	private String filePath;
	private String versionName;

	public SyllabusArchive() {
	}

	public SyllabusArchive(String semester, int year, String filePath) {
		this.semester = semester;
		this.year = year;
		this.filePath = filePath;
	}

	public SyllabusArchive(String semester, int year, String filePath,
			String versionName) {
		this.semester = semester;
		this.year = year;
		this.filePath = filePath;
		this.versionName = versionName;
	}

	public Integer getSyllabusArchiveId() {
		return this.syllabusArchiveId;
	}

	public void setSyllabusArchiveId(Integer syllabusArchiveId) {
		this.syllabusArchiveId = syllabusArchiveId;
	}

	public String getSemester() {
		return this.semester;
	}

	public void setSemester(String semester) {
		this.semester = semester;
	}

	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public String getVersionName() {
		return this.versionName;
	}

	public void setVersionName(String versionName) {
		this.versionName = versionName;
	}

}
