package entities.dao;

// Generated Apr 11, 2011 8:27:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TypeofCourse generated by hbm2java
 */
public class TypeofCourse implements java.io.Serializable {

	private Integer typeofCourseId;
	private String typeofCourse;
	private Set courses = new HashSet(0);

	public TypeofCourse() {
	}

	public TypeofCourse(String typeofCourse) {
		this.typeofCourse = typeofCourse;
	}

	public TypeofCourse(String typeofCourse, Set courses) {
		this.typeofCourse = typeofCourse;
		this.courses = courses;
	}

	public Integer getTypeofCourseId() {
		return this.typeofCourseId;
	}

	public void setTypeofCourseId(Integer typeofCourseId) {
		this.typeofCourseId = typeofCourseId;
	}

	public String getTypeofCourse() {
		return this.typeofCourse;
	}

	public void setTypeofCourse(String typeofCourse) {
		this.typeofCourse = typeofCourse;
	}

	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

}
