package entities.DOMAIN;


import java.util.List;

import org.hibernate.Query;


import org.hibernate.SQLQuery;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
//import org.hibernate.transform.Transformers;

import entities.Business.TestUserBusiness;

// Generated Dec 16, 2010 9:24:39 PM by Hibernate Tools 3.4.0.Beta1

/**
 * TestUser generated by hbm2java
 */

@SuppressWarnings("serial")
public class TestUser implements java.io.Serializable {

	private int userId;
	private String userName;
	private String userPass;

	public TestUser() {
	}

	public TestUser(int userId) {
		this.userId = userId;
	}

	public TestUser(int userId, String userName, String userPass) {
		this.userId = userId;
		this.userName = userName;
		this.userPass = userPass;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPass() {
		return this.userPass;
	}

	public void setUserPass(String userPass) {
		this.userPass = userPass;
	}
	
	@SuppressWarnings("unchecked")
	public List<TestUser> queryUser(TestUserBusiness tUserBusiness){
		List<TestUser> result = null;
		Session session = null;
		
		try {
			SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
			session = sessionFactory.openSession();
			//SQLQuery query =(SQLQuery)session.createSQLQuery("call queryUserSP(:uName,:uPass)");		
			
			Query query = session.getNamedQuery("queryUser");
			
			String uName = tUserBusiness.get_userName();
			String uPass = tUserBusiness.get_userPass();
			
			
			query.setParameter("uName", uName);
			query.setParameter("uPass", uPass);
			
		/*	
		 * query.setParameter("uName", uName);
			query.setParameter("uPass", uPass);
			query.setParameter("@total", "@total");*/
			//query.setResultTransformer(Transformers.aliasToBean(TestUser.class));
			 /*
			  * query.setString("userName", tUserBusiness.get_userName());
			    query.setString("userPass", tUserBusiness.get_userPass());
			 */
			
			//query.addEntity(TestUser.class).setParameter("uName", uName);
			//query.addEntity(TestUser.class).setParameter("uPass", uPass);
			
			result =(List<TestUser>) query.list();
			
		} catch (Exception e) {
			// TODO: handle exception
			e.getMessage();
		} 
		return result;
	}
}
