package entities.domain;

// Generated Feb 23, 2011 10:30:46 PM by Hibernate Tools 3.4.0.CR1

/**
 * TestUser generated by hbm2java
 */
public class TestUser implements java.io.Serializable {

	private int userId;
	private String userName;
	private String userPass;

	public TestUser() {
	}

	public TestUser(int userId) {
		this.userId = userId;
	}

	public TestUser(int userId, String userName, String userPass) {
		this.userId = userId;
		this.userName = userName;
		this.userPass = userPass;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPass() {
		return this.userPass;
	}

	public void setUserPass(String userPass) {
		this.userPass = userPass;
	}

}
